# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.13
    hooks:
    -   id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
    -   id: ruff-format
        types_or: [ python, pyi, jupyter ]
-   repo: local
    hooks:
    -   id: check-copyright
        name: Check Copyright
        entry: python3 -m nerfstudio.scripts.licensing.check_copyright
        language: python
        types: [ python ]
